apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: app-config
      mountPath: /etc/config
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo Sidecar running...; sleep 3600; done']
  volumes:
  - name: app-config
    configMap:
      name: my-app-config
